name: flutter_infinite_list
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^6.0.5
  http: ^0.12.0
  equatable: ^1.2.3
  rxdart: ^0.24.0
  flutter_paginator: ^0.0.6
  json_annotation: ^2.2.0
  build_runner: ^1.0.0
  build_runner_core: ^4.0.0
  json_serializable: ^2.0.0
  better_player:
    git: https://github.com/RomanShtyk/betterplayer.git
  audioplayers: ^0.16.1
flutter:
  uses-material-design: true
