name: flutter_infinite_list
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
    path: ../../packages/flutter_bloc
  http: ^0.12.0
  equatable: ^1.2.3
  rxdart: ^0.24.0
  flutter_paginator: ^0.0.6
  json_model: ^0.0.2
  json_annotation: ^2.2.0
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true
